config/routes.rb
SocialChatterExample::Application.routes.draw do
      resources :shipments

    root :to => 'shipments#index'
    match "logout" => "shipments#logout"
    match "post" => "shipments#post"
    match "*rest" => "shipments#index"

end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
  attr_accessible :id, :shipment_date, :shipped
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/shipments_controller.rb
require 'httparty'

class ShipmentsController < ApplicationController
    include Databasedotcom::OAuth2::Helpers
    include HTTParty

    before_filter :init

    def init
        @authenticated = authenticated?
        
        if authenticated?
            @me = me

            # Set up URL and headers for REST calls
            @root_url = client.instance_url + "/services/data/v" +
                client.version
            @options = { 
                :headers => { 
                    'Authorization' => "OAuth #{client.oauth_token}",
                    'Content-Type' => "application/json",
                    'X-PrettyPrint' => "1"
                }
            }
        end
    end

    def logout
        client.logout if authenticated?
    end

    def post
        # Create JSON for REST request
        options = @options
        options.merge!( 
            :body => { 
                :body => { 
                    :messageSegments => [
                        {
                            :type => "Text",
                            :text => params[:content]
                        }
                    ]
                }
            }.to_json
        )

        # Do REST request
        response = HTTParty.post(@root_url + "/chatter/feeds/record/" + 
            params[:parent_id] + "/feed-items", options)
    end

    # GET /shipments
    # GET /shipments.json
    def index
    
        @shipments = Shipment.all
        
        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @shipments }
        end
    end

    # GET /shipments/1
    # GET /shipments/1.json
    def show
        # Get shipment from Postgres DB
        @shipment = Shipment.find(params[:id])
    
        # Get shadow object from database.com
        @shadow_obj = client.query("SELECT Id, Name FROM " +             
            "ShipmentChatter__c WHERE Name = \'" << params[:id] << "\'")
        @id = @shadow_obj[0].Id
    
        # Get Chatter feed for shadow object
        @feed = client.query("SELECT Body, InsertedById FROM " +
            "FeedItem WHERE ParentId = \'" + @id +  "\' ORDER BY CreatedDate")
    
        # Get User list for identifying Chatter post user
        @user_list = Hash.new()
        raw_user_list = client.query("SELECT Id, Name FROM User")
        raw_user_list.each do |user|
            @user_list[user.Id] = user.Name
        end
    
        respond_to do |format|
          format.html # show.html.erb
          format.json { render json: @shipment }
        end
    end

    # GET /shipments/new
    # GET /shipments/new.json
    def new
        @shipment = Shipment.new
        
        respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @shipment }
        end
    end

    # GET /shipments/1/edit
    def edit
        @shipment = Shipment.find(params[:id])
    end

    # POST /shipments
    # POST /shipments.json
    def create
        # Save shipment in Postgres DB
        @shipment = Shipment.new(params[:shipment])

        respond_to do |format|
            if @shipment.save

                # Create JSON for REST request
                options = @options
                options.merge!( 
                    :body => { 
                        :Name => @shipment.id
                    }.to_json
                )
                
                # Do REST request
                response = HTTParty.post(@root_url + 
                    "/sobjects/ShipmentChatter__c", options)
                
                format.html { redirect_to @shipment, notice: 
                    'Shipment was successfully created.' }
                format.json { render json: @shipment, status: :created, 
                    location: @shipment }
            else
                format.html { render action: "new" }
                format.json { render json: @shipment.errors, 
                    status: :unprocessable_entity }
            end
        end
    end

    # PUT /shipments/1
    # PUT /shipments/1.json
    def update
        @shipment = Shipment.find(params[:id])
        
        respond_to do |format|
            if @shipment.update_attributes(params[:shipment])
                format.html { redirect_to @shipment, 
                    notice: 'Shipment was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: "edit" }
                format.json { render json: @shipment.errors, 
                    status: :unprocessable_entity }
            end
        end
    end

    # DELETE /shipments/1
    # DELETE /shipments/1.json
    def destroy
        @shipment = Shipment.find(params[:id])
        @shipment.destroy
        
        respond_to do |format|
            format.html { redirect_to shipments_url }
            format.json { head :no_content }
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialChatterExample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shipments/_form.html.erb
<%= form_for(@shipment) do |f| %>
  <% if @shipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipment.errors.count, "error") %> prohibited this shipment from being saved:</h2>

      <ul>
      <% @shipment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :shipped %><br />
    <%= f.check_box :shipped %>
  </div>
  <div class="field">
    <%= f.label :shipment_date %><br />
    <%= f.date_select :shipment_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shipments/edit.html.erb
<h1>Editing shipment</h1>

<%= render 'form' %>

<%= link_to 'Show', @shipment %> |
<%= link_to 'Back', shipments_path %>

app/views/shipments/index.html.erb
<h1>Listing shipments</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Shipped</th>
    <th>Shipment date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shipments.each do |shipment| %>
  <tr>
    <td><%= shipment.id %></td>
    <td><%= shipment.shipped %></td>
    <td><%= shipment.shipment_date %></td>
    <td><%= link_to 'Show', shipment %></td>
    <td><%= link_to 'Edit', edit_shipment_path(shipment) %></td>
    <td><%= link_to 'Destroy', shipment, method: :delete, data: 
        { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<p><% if @authenticated%>
    You're logged in as <%= @me.username%>. Click <a href="/logout">here</a> to 
    logout.

    <%= yield %>

<% elsif%>
    You're not logged in. Click <a href="/auth/salesforce">here</a> to login.
<% end%></p>

<%= link_to 'New Shipment', new_shipment_path %>

app/views/shipments/logout.html.erb
<h1>Logout Successful</h1>

<p>You have logged out successfully.</p>

<%= link_to 'Back', shipments_path %>

app/views/shipments/new.html.erb
<h1>New shipment</h1>

<%= render 'form' %>

<%= link_to 'Back', shipments_path %>

app/views/shipments/post.html.erb
<h1>Post Successful</h1>

<p>You have posted successfully.</p>

<%= link_to 'Back', shipments_path %>

app/views/shipments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @shipment.id %>
</p>

<p>
  <b>Shipped:</b>
  <%= @shipment.shipped %>
</p>

<p>
  <b>Shipment date:</b>
  <%= @shipment.shipment_date %>
</p>

<h3>Chatter:</h3>

<% @feed.each do |f| %>
    <b><%= @user_list[f.InsertedById] %>:</b> <%= f.Body %><br />
<% end %>

<form action="/post" method="post">
    <input name="parent_id" type="hidden" value="<%= @id %>" />
    <input name="content" type="text"/>
    <%= csrf_meta_tag %>
    <input value="Post" type="submit"/>
</form>

<%= link_to 'Edit', edit_shipment_path(@shipment) %> |
<%= link_to 'Back', shipments_path %>